### ISSUE TITLE
IntelliSense can't find includes

### ISSUE THREAD

**Issue by ipelekhan** [acharluk/easy-cpp-projects#12]
Tried extension today, just wanted to clarify the behavior below is expected or not.

**Expected**: single header libraries are present in autocomplete automatically
**Actual**: you need to add include path `"${workspaceFolder}/include"` to the `c_cpp_properties.json`

If that's expected, are there any reasons not to put this line into property file on the project generation step?

By the way, I am running latest VS Code on Mac.

**Comment by zipzit** [comment]
ipelekhan, I'm way confused.  
--How exactly does one include compiled libraries located elsewhere on the drive?
--Is there a mechanism within EasyCpp that generates the c_cpp_properties.json?
--If you have to use c_cpp_properties.json for effective compilation, and that isn't integrated somehow to easy-cpp-projects, why would we use easy-cpp-projects in the first place?  

(I would have thought if c_cpp_properties.json is used everywhere, that Easy-CPP-Project populates that file with content from the Makefile)

Or am I just doing this wrong?  Many thx .

**Comment by acharluk** [comment]
Easy C++ Projects does not provide a `c_cpp_properties.json` file, that file comes from the [C/C++](https://github.com/Microsoft/vscode-cpptools) extension.

As far as I've tried, intellisense (auto completion) can find any header file inside the `src` and `include` folders, even if it is inside a subfolder, so it may be a problem with the C/C++ extension itself.

I am still working on better and updated templates to work with newer versions of VSCode :smiley:

**Comment by ipelekhan** [comment]
@acharluk, okay got it! Thanks for clarification. Currently fresh created project looks like this for me:
![Screenshot 2019-06-27 at 07 30 34](https://user-images.githubusercontent.com/2616427/60239412-e75e6c80-98ad-11e9-841a-6caeae87f464.png)

Although it's easy to fix using automated VSCode fix button. And by the way, currently `c_cpp_properties.json` is not generated by default with C/C++ extension (that's why I assumed that it was generated by Easy C++ Projects in the first place).
Thanks again.
