### ISSUE TITLE
Not able to create easy cpp project

### ISSUE THREAD

**Issue by rqg0717** [acharluk/easy-cpp-projects#13]
Easy C++ Projects error: Could not fetch 'files.json' from GitHub Error: FetchError: request to https://raw.githubusercontent.com/acharluk/easy-cpp-projects/master/templates/project/files.json failed, reason: certificate signature failure

**Comment by bryantbunderson** [comment]
I get the same error trying to use easy-cpp-projects on a computer without access to the Internet. It surprised me. I didn't realize that the extension pulled active content from github. Is there a way to download required files? Perhaps clone the repo and use it locally?

**Comment by acharluk** [comment]
Related to #7 
Also solved on version 1.7.0!
