### ISSUE TITLE
Always creates C++ project in the first folder

### ISSUE THREAD

**Issue by leongor** [acharluk/easy-cpp-projects#2]
I have more than one folder in my workspace.
When I run `Create C++ project`, it's always created in the first folder, not in the selected one.

**Comment by acharluk** [comment]
Hello @leongor , the extension only support one folder at this moment. I'll look into including workspace support as soon as I can and hopefully release an update in a few days, thank you!

**Comment by acharluk** [comment]
This issue is now fixed in [this commit](https://github.com/acharluk/easy-cpp-projects/commit/bbf8e2fcc14b89e9e898d26c9e7f9c585d7561d7). It has also been updated in the Marketplace.

**Comment by leongor** [comment]
Thank you - works perfectly!
