### ISSUE TITLE
Add Debug Configurations

### ISSUE THREAD

**Issue by thegabriele97** [acharluk/easy-cpp-projects#5]
Hi, is possible to add automatic creation of launch.json for debugging?

**Comment by acharluk** [comment]
Debugging is already supported. Here are the `launch.json` for [Windows](https://github.com/acharluk/easy-cpp-projects/blob/master/templates/project/msvc/launch.json), [Linux](https://github.com/acharluk/easy-cpp-projects/blob/master/templates/project/gcc/launch.json) and [macOS](https://github.com/acharluk/easy-cpp-projects/blob/master/templates/project/clang/launch.json)

Are you having a specific problem with debugging?

**Comment by fhammoud** [comment]
Hi acharluk. I am using Windows 10 and have WSL Ubuntu installed. Using your extension when I create a new C++ project then select WSL I don't get a launch.json.

**Comment by acharluk** [comment]
Hi @fhammoud , I haven't yet added a launch.json to WSL because path translation doesn't work perfectly on vscode. However you can use a template like this one, you just need to set the exact path of your project (I'm still figuring out if I can add this to the extension so it can set the path without needing the user setting it):

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "C++ Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "/mnt/c/path/to/your/project/bin/main",
            "args": ["-fThreading"],
            "stopAtEntry": false,
            "cwd": "/mnt/c/path/to/your/project",
            "environment": [],
            "externalConsole": true,
            "windows": {
                "MIMode": "gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            },
            "pipeTransport": {
                "pipeCwd": "",
                "pipeProgram": "c:\\windows\\sysnative\\bash.exe",
                "pipeArgs": ["-c"],
                "debuggerPath": "/usr/bin/gdb"
            },
            "sourceFileMap": {
                "/mnt/c": "c:\\"
            }
        }
    ]
}
```
