### ISSUE TITLE
Feature request: Allowing custom templates

### ISSUE THREAD

**Issue by TaylerUva** [acharluk/easy-cpp-projects#6]
I would love it if you could configure the files that are created with Easy C++ Projects. Having the ability to customize the default Makefile created or adding your own template cpp files would be super helpful.

**Comment by acharluk** [comment]
Hi @TaylerUva !

This is definitely a great idea! I've been thinking of adding a feature like this, but have been working on others. My idea is having some folder with custom templates for any new project, and that they can be created with the extension itself. It will take a bit of time but it is on my todo list.

Thank you!

**Comment by TaylerUva** [comment]
@acharluk awesome! I love your extension, it's very powerful and I look forward to seeing it's improvements in the future!

**Comment by TaylerUva** [comment]
As an expansion of that idea, theoretically you could also expand this for other languages in the future. As the nicest part of this extension in my opinion are the automatic set up of the task.json, launch.json and template starting file. If you added the ability to make or set your own versions of those files you could allow the end user to apply it to any language. I use this extension so I don't have to create the task.json, and makefile every time I want a new project. Plus the buttons at the bottom are really nice.

I know this may not be something you want to invest time into but thought I'd share anyway.

**Comment by acharluk** [comment]
This has been implemented on version 1.7.0!
