### ISSUE TITLE
Feature Request: Store the template files locally to allow for offline use

### ISSUE THREAD

**Issue by TaylerUva** [acharluk/easy-cpp-projects#7]
Currently it is not possible to use some files of this extension when your computer is disconnected from the internet. If you were able to store the templates locally and read from those files it could alleviate this issue. Even if you only need to be connected once for initial download of those files that would be a huge help.

**Comment by hubbiton** [comment]
I second that. It also would allow to modify templates - for instance, my compiler only supports c++14, so I have to change it manually in the makefile for every project.

**Comment by acharluk** [comment]
Sorry for the late response, I've been really busy this last months and haven't been able to work on this project for a while.
I am now back and this issue is resolved on version 1.7.0, thank you!
